pipeline {
    agent any

    stages {
        stage('pre-build') {
            steps {
                sh '''rm -rf docker-java
                git clone https://github.com/Ikrao/docker-java.git'''
            }
        }
        stage('mvn-build') {
            steps {
                sh '''cd docker-java/docker-spring-boot
                mvn clean install'''
            }
            
        }
        stage('docker-build') {
            steps {
                sh '''cd docker-java/docker-spring-boot
                sudo docker build -t helloworld:latest .'''
            }
            
        }
        stage('deploy') {
            steps {
                sh '''sudo docker run -d --name fhp -p 8091:8080 helloworld:latest'''
            }
        }
    }
}
