---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  namespace: default
  labels:
    app: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-container
        image: 815862825235.dkr.ecr.us-east-1.amazonaws.com/spring:latest
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 8080
      imagePullSecrets:
          - name: my-sec
